# Generated by Django 4.2.7 on 2023-11-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo_menu', '0002_alter_menudrevo_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menudrevo',
            old_name='title',
            new_name='menu_title',
        ),
    ]
